### ISSUE TITLE
Doc

### ISSUE THREAD

**Issue by Tvax** [Tvax/laravel-gravatar#12]
Un document expliquant votre projet pour une personne qui n’y a pas participé (format 
HTML ou PDF)
Quoi consiste projet
Expliquer rapidement comment ca marche

Faire la doc dans l'application

**Comment by cfer97** [comment]
https://docs.google.com/document/d/1A-6w-hZpEVFsBiM9oMWwMSIquPgRGA1rJHOTua4T9qk/edit?usp=sharing
